// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package handler

import (
	"fmt"
	"log"
	"mockserver/internal/handler/assert"
	"mockserver/internal/logging"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/optionalnullable"
	"mockserver/internal/sdk/types"
	"mockserver/internal/sdk/utils"
	"mockserver/internal/tracking"
	"net/http"
)

func pathGetEcommerceOrdersID(dir *logging.HTTPFileDirectory, rt *tracking.RequestTracker) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		test := req.Header.Get("x-speakeasy-test-name")
		instanceID := req.Header.Get("x-speakeasy-test-instance-id")

		count := rt.GetRequestCount(test, instanceID)

		switch fmt.Sprintf("%s[%d]", test, count) {
		case "ecommerce.ordersOne[0]":
			dir.HandlerFunc("ecommerce.ordersOne", testEcommerceOrdersOneEcommerceOrdersOne0)(w, req)
		default:
			http.Error(w, fmt.Sprintf("Unknown test: %s[%d]", test, count), http.StatusBadRequest)
		}
	}
}

func testEcommerceOrdersOneEcommerceOrdersOne0(w http.ResponseWriter, req *http.Request) {
	if err := assert.SecurityAuthorizationHeader(req, false, "Bearer"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusUnauthorized)
		return
	}
	if err := assert.AcceptHeader(req, []string{"application/json"}); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if err := assert.HeaderExists(req, "User-Agent"); err != nil {
		log.Printf("assertion error: %s\n", err)
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	var respBody *components.GetEcommerceOrderResponse = &components.GetEcommerceOrderResponse{
		StatusCode: 200,
		Status:     "OK",
		Service:    "shopify",
		Resource:   "orders",
		Operation:  "one",
		Data: components.EcommerceOrder{
			ID:          "12345",
			OrderNumber: optionalnullable.From(types.String("123456789")),
			Currency:    optionalnullable.From(components.CurrencyUsd.ToPointer()),
			Discounts: []components.EcommerceDiscount{
				components.EcommerceDiscount{
					Code:       optionalnullable.From(types.String("SUMMER20")),
					Amount:     optionalnullable.From(types.String("5.99")),
					Percentage: optionalnullable.From(types.String("0.1")),
				},
				components.EcommerceDiscount{
					Code:       optionalnullable.From(types.String("SUMMER20")),
					Amount:     optionalnullable.From(types.String("5.99")),
					Percentage: optionalnullable.From(types.String("0.1")),
				},
				components.EcommerceDiscount{
					Code:       optionalnullable.From(types.String("SUMMER20")),
					Amount:     optionalnullable.From(types.String("5.99")),
					Percentage: optionalnullable.From(types.String("0.1")),
				},
			},
			SubTotal:          optionalnullable.From(types.String("45.17")),
			ShippingCost:      optionalnullable.From(types.String("5.17")),
			CouponDiscount:    optionalnullable.From(types.String("5.5")),
			TotalDiscount:     optionalnullable.From(types.String("5.5")),
			TotalTax:          optionalnullable.From(types.String("5.16")),
			TotalAmount:       optionalnullable.From(types.String("50.17")),
			RefundedAmount:    optionalnullable.From(types.String("5.5")),
			Status:            optionalnullable.From(components.EcommerceOrderStatusActive.ToPointer()),
			PaymentStatus:     optionalnullable.From(components.EcommerceOrderPaymentStatusPaid.ToPointer()),
			FulfillmentStatus: optionalnullable.From(components.FulfillmentStatusShipped.ToPointer()),
			PaymentMethod:     optionalnullable.From(types.String("credit_card")),
			Customer: &components.LinkedEcommerceCustomer{
				ID:          optionalnullable.From(types.String("12345")),
				Name:        optionalnullable.From(types.String("John Doe")),
				FirstName:   optionalnullable.From(types.String("John")),
				LastName:    optionalnullable.From(types.String("Doe")),
				CompanyName: optionalnullable.From(types.String("Acme Inc.")),
				PhoneNumbers: optionalnullable.From(types.Pointer([]components.PhoneNumber{
					components.PhoneNumber{
						ID:          optionalnullable.From(types.String("12345")),
						CountryCode: optionalnullable.From(types.String("1")),
						AreaCode:    optionalnullable.From(types.String("323")),
						Number:      "111-111-1111",
						Extension:   optionalnullable.From(types.String("105")),
						Type:        optionalnullable.From(components.PhoneNumberTypePrimary.ToPointer()),
					},
					components.PhoneNumber{
						ID:          optionalnullable.From(types.String("12345")),
						CountryCode: optionalnullable.From(types.String("1")),
						AreaCode:    optionalnullable.From(types.String("323")),
						Number:      "111-111-1111",
						Extension:   optionalnullable.From(types.String("105")),
						Type:        optionalnullable.From(components.PhoneNumberTypePrimary.ToPointer()),
					},
				})),
				Emails: optionalnullable.From(types.Pointer([]components.Email{
					components.Email{
						ID:    optionalnullable.From(types.String("123")),
						Email: types.String("elon@musk.com"),
						Type:  optionalnullable.From(components.EmailTypePrimary.ToPointer()),
					},
					components.Email{
						ID:    optionalnullable.From(types.String("123")),
						Email: types.String("elon@musk.com"),
						Type:  optionalnullable.From(components.EmailTypePrimary.ToPointer()),
					},
				})),
			},
			BillingAddress: &components.EcommerceAddress{
				Line1:       optionalnullable.From(types.String("123 Main Street")),
				Line2:       optionalnullable.From(types.String("Apt 1")),
				CompanyName: optionalnullable.From(types.String("Acme Inc.")),
				City:        optionalnullable.From(types.String("New York")),
				State:       optionalnullable.From(types.String("NY")),
				PostalCode:  optionalnullable.From(types.String("10001")),
				Country:     optionalnullable.From(types.String("US")),
			},
			ShippingAddress: &components.EcommerceAddress{
				Line1:       optionalnullable.From(types.String("123 Main Street")),
				Line2:       optionalnullable.From(types.String("Apt 1")),
				CompanyName: optionalnullable.From(types.String("Acme Inc.")),
				City:        optionalnullable.From(types.String("New York")),
				State:       optionalnullable.From(types.String("NY")),
				PostalCode:  optionalnullable.From(types.String("10001")),
				Country:     optionalnullable.From(types.String("US")),
			},
			Tracking: []components.TrackingItem{
				components.TrackingItem{
					Provider:  types.String("UPS"),
					Number:    types.String("1Z9999999999999999"),
					URL:       optionalnullable.From(types.String("https://www.ups.com/track?tracknum=1Z9999999999999999")),
					UpdatedAt: optionalnullable.From(types.MustNewTimeFromString("2020-09-30T07:43:32.000Z")),
				},
				components.TrackingItem{
					Provider:  types.String("UPS"),
					Number:    types.String("1Z9999999999999999"),
					URL:       optionalnullable.From(types.String("https://www.ups.com/track?tracknum=1Z9999999999999999")),
					UpdatedAt: optionalnullable.From(types.MustNewTimeFromString("2020-09-30T07:43:32.000Z")),
				},
			},
			LineItems: []components.EcommerceOrderLineItem{
				components.EcommerceOrderLineItem{
					ID:          optionalnullable.From(types.String("12345")),
					ProductID:   optionalnullable.From(types.String("def456")),
					VariantID:   optionalnullable.From(types.String("ghi789")),
					Sku:         optionalnullable.From(types.String("MBP123-16GB-SILVER-13")),
					Name:        optionalnullable.From(types.String("Midnight 16inch MacBook Pro")),
					Description: optionalnullable.From(types.String("Powerful and portable, the MacBook Pro is perfect for professionals and creatives.")),
					Options: []components.EcommerceOrderLineItemOption{
						components.EcommerceOrderLineItemOption{
							ID:    optionalnullable.From(types.String("jkl012")),
							Name:  optionalnullable.From(types.String("Color")),
							Value: optionalnullable.From(types.String("Silver")),
						},
						components.EcommerceOrderLineItemOption{
							ID:    optionalnullable.From(types.String("jkl012")),
							Name:  optionalnullable.From(types.String("Color")),
							Value: optionalnullable.From(types.String("Silver")),
						},
					},
					Quantity:         types.String("2"),
					UnitPrice:        optionalnullable.From(types.String("19.99")),
					TaxRate:          optionalnullable.From(types.String("0.08")),
					TaxAmount:        optionalnullable.From(types.String("1.6")),
					IsRefunded:       optionalnullable.From(types.Bool(false)),
					RefundedAmount:   optionalnullable.From(types.String("0")),
					RefundedQuantity: optionalnullable.From(types.String("0")),
					SubTotal:         optionalnullable.From(types.String("43.18")),
					TotalAmount:      optionalnullable.From(types.String("43.18")),
					Discounts: []components.EcommerceDiscount{
						components.EcommerceDiscount{
							Code:       optionalnullable.From(types.String("SUMMER20")),
							Amount:     optionalnullable.From(types.String("5.99")),
							Percentage: optionalnullable.From(types.String("0.1")),
						},
						components.EcommerceDiscount{
							Code:       optionalnullable.From(types.String("SUMMER20")),
							Amount:     optionalnullable.From(types.String("5.99")),
							Percentage: optionalnullable.From(types.String("0.1")),
						},
					},
				},
				components.EcommerceOrderLineItem{
					ID:          optionalnullable.From(types.String("12345")),
					ProductID:   optionalnullable.From(types.String("def456")),
					VariantID:   optionalnullable.From(types.String("ghi789")),
					Sku:         optionalnullable.From(types.String("MBP123-16GB-SILVER-13")),
					Name:        optionalnullable.From(types.String("Midnight 16inch MacBook Pro")),
					Description: optionalnullable.From(types.String("Powerful and portable, the MacBook Pro is perfect for professionals and creatives.")),
					Options: []components.EcommerceOrderLineItemOption{
						components.EcommerceOrderLineItemOption{
							ID:    optionalnullable.From(types.String("jkl012")),
							Name:  optionalnullable.From(types.String("Color")),
							Value: optionalnullable.From(types.String("Silver")),
						},
					},
					Quantity:         types.String("2"),
					UnitPrice:        optionalnullable.From(types.String("19.99")),
					TaxRate:          optionalnullable.From(types.String("0.08")),
					TaxAmount:        optionalnullable.From(types.String("1.6")),
					IsRefunded:       optionalnullable.From(types.Bool(false)),
					RefundedAmount:   optionalnullable.From(types.String("0")),
					RefundedQuantity: optionalnullable.From(types.String("0")),
					SubTotal:         optionalnullable.From(types.String("43.18")),
					TotalAmount:      optionalnullable.From(types.String("43.18")),
					Discounts: []components.EcommerceDiscount{
						components.EcommerceDiscount{
							Code:       optionalnullable.From(types.String("SUMMER20")),
							Amount:     optionalnullable.From(types.String("5.99")),
							Percentage: optionalnullable.From(types.String("0.1")),
						},
					},
				},
				components.EcommerceOrderLineItem{
					ID:          optionalnullable.From(types.String("12345")),
					ProductID:   optionalnullable.From(types.String("def456")),
					VariantID:   optionalnullable.From(types.String("ghi789")),
					Sku:         optionalnullable.From(types.String("MBP123-16GB-SILVER-13")),
					Name:        optionalnullable.From(types.String("Midnight 16inch MacBook Pro")),
					Description: optionalnullable.From(types.String("Powerful and portable, the MacBook Pro is perfect for professionals and creatives.")),
					Options: []components.EcommerceOrderLineItemOption{
						components.EcommerceOrderLineItemOption{
							ID:    optionalnullable.From(types.String("jkl012")),
							Name:  optionalnullable.From(types.String("Color")),
							Value: optionalnullable.From(types.String("Silver")),
						},
						components.EcommerceOrderLineItemOption{
							ID:    optionalnullable.From(types.String("jkl012")),
							Name:  optionalnullable.From(types.String("Color")),
							Value: optionalnullable.From(types.String("Silver")),
						},
						components.EcommerceOrderLineItemOption{
							ID:    optionalnullable.From(types.String("jkl012")),
							Name:  optionalnullable.From(types.String("Color")),
							Value: optionalnullable.From(types.String("Silver")),
						},
					},
					Quantity:         types.String("2"),
					UnitPrice:        optionalnullable.From(types.String("19.99")),
					TaxRate:          optionalnullable.From(types.String("0.08")),
					TaxAmount:        optionalnullable.From(types.String("1.6")),
					IsRefunded:       optionalnullable.From(types.Bool(false)),
					RefundedAmount:   optionalnullable.From(types.String("0")),
					RefundedQuantity: optionalnullable.From(types.String("0")),
					SubTotal:         optionalnullable.From(types.String("43.18")),
					TotalAmount:      optionalnullable.From(types.String("43.18")),
					Discounts: []components.EcommerceDiscount{
						components.EcommerceDiscount{
							Code:       optionalnullable.From(types.String("SUMMER20")),
							Amount:     optionalnullable.From(types.String("5.99")),
							Percentage: optionalnullable.From(types.String("0.1")),
						},
						components.EcommerceDiscount{
							Code:       optionalnullable.From(types.String("SUMMER20")),
							Amount:     optionalnullable.From(types.String("5.99")),
							Percentage: optionalnullable.From(types.String("0.1")),
						},
					},
				},
			},
			Note:      optionalnullable.From(types.String("Special instructions for delivery")),
			CreatedAt: optionalnullable.From(types.MustNewTimeFromString("2020-09-30T07:43:32.000Z")),
			UpdatedAt: optionalnullable.From(types.MustNewTimeFromString("2020-09-30T07:43:32.000Z")),
		},
	}
	respBodyBytes, err := utils.MarshalJSON(respBody, "", true)

	if err != nil {
		http.Error(
			w,
			"Unable to encode response body as JSON: "+err.Error(),
			http.StatusInternalServerError,
		)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(respBodyBytes)
}
