/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AccountingLedgerAccountsAllGlobals = {
  /**
   * ID of the consumer which you want to get or push data from
   */
  consumerId?: string | undefined;
  /**
   * The ID of your Unify application
   */
  appId?: string | undefined;
};

export type AccountingLedgerAccountsAllRequest = {
  /**
   * Include raw response. Mostly used for debugging purposes
   */
  raw?: boolean | undefined;
  /**
   * Provide the service id you want to call (e.g., pipedrive). Only needed when a consumer has activated multiple integrations for a Unified API.
   */
  serviceId?: string | undefined;
  /**
   * Cursor to start from. You can find cursors for next/previous pages in the meta.cursors property of the response.
   */
  cursor?: string | null | undefined;
  /**
   * Number of results to return. Minimum 1, Maximum 200, Default 20
   */
  limit?: number | undefined;
  /**
   * Apply filters
   */
  filter?: components.LedgerAccountsFilter | undefined;
  /**
   * Apply sorting
   */
  sort?: components.LedgerAccountsSort | undefined;
  /**
   * Optional unmapped key/values that will be passed through to downstream as query parameters. Ie: ?pass_through[search]=leads becomes ?search=leads
   */
  passThrough?: { [k: string]: any } | undefined;
  /**
   * The 'fields' parameter allows API users to specify the fields they want to include in the API response. If this parameter is not present, the API will return all available fields. If this parameter is present, only the fields specified in the comma-separated string will be included in the response. Nested properties can also be requested by using a dot notation. <br /><br />Example: `fields=name,email,addresses.city`<br /><br />In the example above, the response will only include the fields "name", "email" and "addresses.city". If any other fields are available, they will be excluded.
   */
  fields?: string | null | undefined;
};

export type AccountingLedgerAccountsAllResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * LedgerAccounts
   */
  getLedgerAccountsResponse?: components.GetLedgerAccountsResponse | undefined;
  /**
   * Unexpected error
   */
  unexpectedErrorResponse?: components.UnexpectedErrorResponse | undefined;
};

/** @internal */
export const AccountingLedgerAccountsAllGlobals$inboundSchema: z.ZodType<
  AccountingLedgerAccountsAllGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  consumerId: z.string().optional(),
  appId: z.string().optional(),
});

/** @internal */
export type AccountingLedgerAccountsAllGlobals$Outbound = {
  consumerId?: string | undefined;
  appId?: string | undefined;
};

/** @internal */
export const AccountingLedgerAccountsAllGlobals$outboundSchema: z.ZodType<
  AccountingLedgerAccountsAllGlobals$Outbound,
  z.ZodTypeDef,
  AccountingLedgerAccountsAllGlobals
> = z.object({
  consumerId: z.string().optional(),
  appId: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AccountingLedgerAccountsAllGlobals$ {
  /** @deprecated use `AccountingLedgerAccountsAllGlobals$inboundSchema` instead. */
  export const inboundSchema = AccountingLedgerAccountsAllGlobals$inboundSchema;
  /** @deprecated use `AccountingLedgerAccountsAllGlobals$outboundSchema` instead. */
  export const outboundSchema =
    AccountingLedgerAccountsAllGlobals$outboundSchema;
  /** @deprecated use `AccountingLedgerAccountsAllGlobals$Outbound` instead. */
  export type Outbound = AccountingLedgerAccountsAllGlobals$Outbound;
}

export function accountingLedgerAccountsAllGlobalsToJSON(
  accountingLedgerAccountsAllGlobals: AccountingLedgerAccountsAllGlobals,
): string {
  return JSON.stringify(
    AccountingLedgerAccountsAllGlobals$outboundSchema.parse(
      accountingLedgerAccountsAllGlobals,
    ),
  );
}

export function accountingLedgerAccountsAllGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<AccountingLedgerAccountsAllGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      AccountingLedgerAccountsAllGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountingLedgerAccountsAllGlobals' from JSON`,
  );
}

/** @internal */
export const AccountingLedgerAccountsAllRequest$inboundSchema: z.ZodType<
  AccountingLedgerAccountsAllRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  raw: z.boolean().default(false),
  serviceId: z.string().optional(),
  cursor: z.nullable(z.string()).optional(),
  limit: z.number().int().default(20),
  filter: components.LedgerAccountsFilter$inboundSchema.optional(),
  sort: components.LedgerAccountsSort$inboundSchema.optional(),
  pass_through: z.record(z.any()).optional(),
  fields: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "pass_through": "passThrough",
  });
});

/** @internal */
export type AccountingLedgerAccountsAllRequest$Outbound = {
  raw: boolean;
  serviceId?: string | undefined;
  cursor?: string | null | undefined;
  limit: number;
  filter?: components.LedgerAccountsFilter$Outbound | undefined;
  sort?: components.LedgerAccountsSort$Outbound | undefined;
  pass_through?: { [k: string]: any } | undefined;
  fields?: string | null | undefined;
};

/** @internal */
export const AccountingLedgerAccountsAllRequest$outboundSchema: z.ZodType<
  AccountingLedgerAccountsAllRequest$Outbound,
  z.ZodTypeDef,
  AccountingLedgerAccountsAllRequest
> = z.object({
  raw: z.boolean().default(false),
  serviceId: z.string().optional(),
  cursor: z.nullable(z.string()).optional(),
  limit: z.number().int().default(20),
  filter: components.LedgerAccountsFilter$outboundSchema.optional(),
  sort: components.LedgerAccountsSort$outboundSchema.optional(),
  passThrough: z.record(z.any()).optional(),
  fields: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    passThrough: "pass_through",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AccountingLedgerAccountsAllRequest$ {
  /** @deprecated use `AccountingLedgerAccountsAllRequest$inboundSchema` instead. */
  export const inboundSchema = AccountingLedgerAccountsAllRequest$inboundSchema;
  /** @deprecated use `AccountingLedgerAccountsAllRequest$outboundSchema` instead. */
  export const outboundSchema =
    AccountingLedgerAccountsAllRequest$outboundSchema;
  /** @deprecated use `AccountingLedgerAccountsAllRequest$Outbound` instead. */
  export type Outbound = AccountingLedgerAccountsAllRequest$Outbound;
}

export function accountingLedgerAccountsAllRequestToJSON(
  accountingLedgerAccountsAllRequest: AccountingLedgerAccountsAllRequest,
): string {
  return JSON.stringify(
    AccountingLedgerAccountsAllRequest$outboundSchema.parse(
      accountingLedgerAccountsAllRequest,
    ),
  );
}

export function accountingLedgerAccountsAllRequestFromJSON(
  jsonString: string,
): SafeParseResult<AccountingLedgerAccountsAllRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      AccountingLedgerAccountsAllRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountingLedgerAccountsAllRequest' from JSON`,
  );
}

/** @internal */
export const AccountingLedgerAccountsAllResponse$inboundSchema: z.ZodType<
  AccountingLedgerAccountsAllResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  GetLedgerAccountsResponse: components.GetLedgerAccountsResponse$inboundSchema
    .optional(),
  UnexpectedErrorResponse: components.UnexpectedErrorResponse$inboundSchema
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "GetLedgerAccountsResponse": "getLedgerAccountsResponse",
    "UnexpectedErrorResponse": "unexpectedErrorResponse",
  });
});

/** @internal */
export type AccountingLedgerAccountsAllResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  GetLedgerAccountsResponse?:
    | components.GetLedgerAccountsResponse$Outbound
    | undefined;
  UnexpectedErrorResponse?:
    | components.UnexpectedErrorResponse$Outbound
    | undefined;
};

/** @internal */
export const AccountingLedgerAccountsAllResponse$outboundSchema: z.ZodType<
  AccountingLedgerAccountsAllResponse$Outbound,
  z.ZodTypeDef,
  AccountingLedgerAccountsAllResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  getLedgerAccountsResponse: components.GetLedgerAccountsResponse$outboundSchema
    .optional(),
  unexpectedErrorResponse: components.UnexpectedErrorResponse$outboundSchema
    .optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    getLedgerAccountsResponse: "GetLedgerAccountsResponse",
    unexpectedErrorResponse: "UnexpectedErrorResponse",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AccountingLedgerAccountsAllResponse$ {
  /** @deprecated use `AccountingLedgerAccountsAllResponse$inboundSchema` instead. */
  export const inboundSchema =
    AccountingLedgerAccountsAllResponse$inboundSchema;
  /** @deprecated use `AccountingLedgerAccountsAllResponse$outboundSchema` instead. */
  export const outboundSchema =
    AccountingLedgerAccountsAllResponse$outboundSchema;
  /** @deprecated use `AccountingLedgerAccountsAllResponse$Outbound` instead. */
  export type Outbound = AccountingLedgerAccountsAllResponse$Outbound;
}

export function accountingLedgerAccountsAllResponseToJSON(
  accountingLedgerAccountsAllResponse: AccountingLedgerAccountsAllResponse,
): string {
  return JSON.stringify(
    AccountingLedgerAccountsAllResponse$outboundSchema.parse(
      accountingLedgerAccountsAllResponse,
    ),
  );
}

export function accountingLedgerAccountsAllResponseFromJSON(
  jsonString: string,
): SafeParseResult<AccountingLedgerAccountsAllResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      AccountingLedgerAccountsAllResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountingLedgerAccountsAllResponse' from JSON`,
  );
}
