/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type CrmActivitiesAllGlobals = {
  /**
   * ID of the consumer which you want to get or push data from
   */
  customerId?: string | undefined;
  /**
   * The ID of your Unify application
   */
  appId?: string | undefined;
};

export type CrmActivitiesAllRequest = {
  /**
   * Include raw response. Mostly used for debugging purposes
   */
  raw?: boolean | undefined;
  /**
   * Provide the service id you want to call (e.g., pipedrive). Only needed when a consumer has activated multiple integrations for a Unified API.
   */
  serviceId?: string | undefined;
  /**
   * Cursor to start from. You can find cursors for next/previous pages in the meta.cursors property of the response.
   */
  cursor?: string | null | undefined;
  /**
   * Number of results to return. Minimum 1, Maximum 200, Default 20
   */
  limit?: number | undefined;
  /**
   * Apply filters
   */
  filter?: components.ActivitiesFilter | undefined;
  /**
   * Apply sorting
   */
  sort?: components.ActivitiesSort | undefined;
  /**
   * Optional unmapped key/values that will be passed through to downstream as query parameters. Ie: ?pass_through[search]=leads becomes ?search=leads
   */
  passThrough?: { [k: string]: any } | undefined;
  /**
   * The 'fields' parameter allows API users to specify the fields they want to include in the API response. If this parameter is not present, the API will return all available fields. If this parameter is present, only the fields specified in the comma-separated string will be included in the response. Nested properties can also be requested by using a dot notation. <br /><br />Example: `fields=name,email,addresses.city`<br /><br />In the example above, the response will only include the fields "name", "email" and "addresses.city". If any other fields are available, they will be excluded.
   */
  fields?: string | null | undefined;
};

export type CrmActivitiesAllResponse =
  | components.UnexpectedErrorResponse
  | components.GetActivitiesResponse;

/** @internal */
export const CrmActivitiesAllGlobals$inboundSchema: z.ZodType<
  CrmActivitiesAllGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  customerId: z.string().optional(),
  appId: z.string().optional(),
});

/** @internal */
export type CrmActivitiesAllGlobals$Outbound = {
  customerId?: string | undefined;
  appId?: string | undefined;
};

/** @internal */
export const CrmActivitiesAllGlobals$outboundSchema: z.ZodType<
  CrmActivitiesAllGlobals$Outbound,
  z.ZodTypeDef,
  CrmActivitiesAllGlobals
> = z.object({
  customerId: z.string().optional(),
  appId: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CrmActivitiesAllGlobals$ {
  /** @deprecated use `CrmActivitiesAllGlobals$inboundSchema` instead. */
  export const inboundSchema = CrmActivitiesAllGlobals$inboundSchema;
  /** @deprecated use `CrmActivitiesAllGlobals$outboundSchema` instead. */
  export const outboundSchema = CrmActivitiesAllGlobals$outboundSchema;
  /** @deprecated use `CrmActivitiesAllGlobals$Outbound` instead. */
  export type Outbound = CrmActivitiesAllGlobals$Outbound;
}

/** @internal */
export const CrmActivitiesAllRequest$inboundSchema: z.ZodType<
  CrmActivitiesAllRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  raw: z.boolean().default(false),
  serviceId: z.string().optional(),
  cursor: z.nullable(z.string()).optional(),
  limit: z.number().int().default(20),
  filter: components.ActivitiesFilter$inboundSchema.optional(),
  sort: components.ActivitiesSort$inboundSchema.optional(),
  pass_through: z.record(z.any()).optional(),
  fields: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "pass_through": "passThrough",
  });
});

/** @internal */
export type CrmActivitiesAllRequest$Outbound = {
  raw: boolean;
  serviceId?: string | undefined;
  cursor?: string | null | undefined;
  limit: number;
  filter?: components.ActivitiesFilter$Outbound | undefined;
  sort?: components.ActivitiesSort$Outbound | undefined;
  pass_through?: { [k: string]: any } | undefined;
  fields?: string | null | undefined;
};

/** @internal */
export const CrmActivitiesAllRequest$outboundSchema: z.ZodType<
  CrmActivitiesAllRequest$Outbound,
  z.ZodTypeDef,
  CrmActivitiesAllRequest
> = z.object({
  raw: z.boolean().default(false),
  serviceId: z.string().optional(),
  cursor: z.nullable(z.string()).optional(),
  limit: z.number().int().default(20),
  filter: components.ActivitiesFilter$outboundSchema.optional(),
  sort: components.ActivitiesSort$outboundSchema.optional(),
  passThrough: z.record(z.any()).optional(),
  fields: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    passThrough: "pass_through",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CrmActivitiesAllRequest$ {
  /** @deprecated use `CrmActivitiesAllRequest$inboundSchema` instead. */
  export const inboundSchema = CrmActivitiesAllRequest$inboundSchema;
  /** @deprecated use `CrmActivitiesAllRequest$outboundSchema` instead. */
  export const outboundSchema = CrmActivitiesAllRequest$outboundSchema;
  /** @deprecated use `CrmActivitiesAllRequest$Outbound` instead. */
  export type Outbound = CrmActivitiesAllRequest$Outbound;
}

/** @internal */
export const CrmActivitiesAllResponse$inboundSchema: z.ZodType<
  CrmActivitiesAllResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  components.UnexpectedErrorResponse$inboundSchema,
  components.GetActivitiesResponse$inboundSchema,
]);

/** @internal */
export type CrmActivitiesAllResponse$Outbound =
  | components.UnexpectedErrorResponse$Outbound
  | components.GetActivitiesResponse$Outbound;

/** @internal */
export const CrmActivitiesAllResponse$outboundSchema: z.ZodType<
  CrmActivitiesAllResponse$Outbound,
  z.ZodTypeDef,
  CrmActivitiesAllResponse
> = z.union([
  components.UnexpectedErrorResponse$outboundSchema,
  components.GetActivitiesResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CrmActivitiesAllResponse$ {
  /** @deprecated use `CrmActivitiesAllResponse$inboundSchema` instead. */
  export const inboundSchema = CrmActivitiesAllResponse$inboundSchema;
  /** @deprecated use `CrmActivitiesAllResponse$outboundSchema` instead. */
  export const outboundSchema = CrmActivitiesAllResponse$outboundSchema;
  /** @deprecated use `CrmActivitiesAllResponse$Outbound` instead. */
  export type Outbound = CrmActivitiesAllResponse$Outbound;
}
