/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type IssueTrackingCollectionTagsAllGlobals = {
  /**
   * ID of the consumer which you want to get or push data from
   */
  customerId?: string | undefined;
  /**
   * The ID of your Unify application
   */
  appId?: string | undefined;
};

export type IssueTrackingCollectionTagsAllRequest = {
  /**
   * The collection ID
   */
  collectionId: string;
  /**
   * Include raw response. Mostly used for debugging purposes
   */
  raw?: boolean | undefined;
  /**
   * Provide the service id you want to call (e.g., pipedrive). Only needed when a consumer has activated multiple integrations for a Unified API.
   */
  serviceId?: string | undefined;
  /**
   * Cursor to start from. You can find cursors for next/previous pages in the meta.cursors property of the response.
   */
  cursor?: string | null | undefined;
  /**
   * Number of results to return. Minimum 1, Maximum 200, Default 20
   */
  limit?: number | undefined;
  /**
   * Optional unmapped key/values that will be passed through to downstream as query parameters. Ie: ?pass_through[search]=leads becomes ?search=leads
   */
  passThrough?: { [k: string]: any } | undefined;
  /**
   * The 'fields' parameter allows API users to specify the fields they want to include in the API response. If this parameter is not present, the API will return all available fields. If this parameter is present, only the fields specified in the comma-separated string will be included in the response. Nested properties can also be requested by using a dot notation. <br /><br />Example: `fields=name,email,addresses.city`<br /><br />In the example above, the response will only include the fields "name", "email" and "addresses.city". If any other fields are available, they will be excluded.
   */
  fields?: string | null | undefined;
};

export type IssueTrackingCollectionTagsAllResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * List Tags
   */
  getCollectionTagsResponse?: components.GetCollectionTagsResponse | undefined;
  /**
   * Unexpected error
   */
  unexpectedErrorResponse?: components.UnexpectedErrorResponse | undefined;
};

/** @internal */
export const IssueTrackingCollectionTagsAllGlobals$inboundSchema: z.ZodType<
  IssueTrackingCollectionTagsAllGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  customerId: z.string().optional(),
  appId: z.string().optional(),
});

/** @internal */
export type IssueTrackingCollectionTagsAllGlobals$Outbound = {
  customerId?: string | undefined;
  appId?: string | undefined;
};

/** @internal */
export const IssueTrackingCollectionTagsAllGlobals$outboundSchema: z.ZodType<
  IssueTrackingCollectionTagsAllGlobals$Outbound,
  z.ZodTypeDef,
  IssueTrackingCollectionTagsAllGlobals
> = z.object({
  customerId: z.string().optional(),
  appId: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IssueTrackingCollectionTagsAllGlobals$ {
  /** @deprecated use `IssueTrackingCollectionTagsAllGlobals$inboundSchema` instead. */
  export const inboundSchema =
    IssueTrackingCollectionTagsAllGlobals$inboundSchema;
  /** @deprecated use `IssueTrackingCollectionTagsAllGlobals$outboundSchema` instead. */
  export const outboundSchema =
    IssueTrackingCollectionTagsAllGlobals$outboundSchema;
  /** @deprecated use `IssueTrackingCollectionTagsAllGlobals$Outbound` instead. */
  export type Outbound = IssueTrackingCollectionTagsAllGlobals$Outbound;
}

/** @internal */
export const IssueTrackingCollectionTagsAllRequest$inboundSchema: z.ZodType<
  IssueTrackingCollectionTagsAllRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  collection_id: z.string(),
  raw: z.boolean().default(false),
  serviceId: z.string().optional(),
  cursor: z.nullable(z.string()).optional(),
  limit: z.number().int().default(20),
  pass_through: z.record(z.any()).optional(),
  fields: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "collection_id": "collectionId",
    "pass_through": "passThrough",
  });
});

/** @internal */
export type IssueTrackingCollectionTagsAllRequest$Outbound = {
  collection_id: string;
  raw: boolean;
  serviceId?: string | undefined;
  cursor?: string | null | undefined;
  limit: number;
  pass_through?: { [k: string]: any } | undefined;
  fields?: string | null | undefined;
};

/** @internal */
export const IssueTrackingCollectionTagsAllRequest$outboundSchema: z.ZodType<
  IssueTrackingCollectionTagsAllRequest$Outbound,
  z.ZodTypeDef,
  IssueTrackingCollectionTagsAllRequest
> = z.object({
  collectionId: z.string(),
  raw: z.boolean().default(false),
  serviceId: z.string().optional(),
  cursor: z.nullable(z.string()).optional(),
  limit: z.number().int().default(20),
  passThrough: z.record(z.any()).optional(),
  fields: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    collectionId: "collection_id",
    passThrough: "pass_through",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IssueTrackingCollectionTagsAllRequest$ {
  /** @deprecated use `IssueTrackingCollectionTagsAllRequest$inboundSchema` instead. */
  export const inboundSchema =
    IssueTrackingCollectionTagsAllRequest$inboundSchema;
  /** @deprecated use `IssueTrackingCollectionTagsAllRequest$outboundSchema` instead. */
  export const outboundSchema =
    IssueTrackingCollectionTagsAllRequest$outboundSchema;
  /** @deprecated use `IssueTrackingCollectionTagsAllRequest$Outbound` instead. */
  export type Outbound = IssueTrackingCollectionTagsAllRequest$Outbound;
}

/** @internal */
export const IssueTrackingCollectionTagsAllResponse$inboundSchema: z.ZodType<
  IssueTrackingCollectionTagsAllResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  GetCollectionTagsResponse: components.GetCollectionTagsResponse$inboundSchema
    .optional(),
  UnexpectedErrorResponse: components.UnexpectedErrorResponse$inboundSchema
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "GetCollectionTagsResponse": "getCollectionTagsResponse",
    "UnexpectedErrorResponse": "unexpectedErrorResponse",
  });
});

/** @internal */
export type IssueTrackingCollectionTagsAllResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  GetCollectionTagsResponse?:
    | components.GetCollectionTagsResponse$Outbound
    | undefined;
  UnexpectedErrorResponse?:
    | components.UnexpectedErrorResponse$Outbound
    | undefined;
};

/** @internal */
export const IssueTrackingCollectionTagsAllResponse$outboundSchema: z.ZodType<
  IssueTrackingCollectionTagsAllResponse$Outbound,
  z.ZodTypeDef,
  IssueTrackingCollectionTagsAllResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  getCollectionTagsResponse: components.GetCollectionTagsResponse$outboundSchema
    .optional(),
  unexpectedErrorResponse: components.UnexpectedErrorResponse$outboundSchema
    .optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    getCollectionTagsResponse: "GetCollectionTagsResponse",
    unexpectedErrorResponse: "UnexpectedErrorResponse",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IssueTrackingCollectionTagsAllResponse$ {
  /** @deprecated use `IssueTrackingCollectionTagsAllResponse$inboundSchema` instead. */
  export const inboundSchema =
    IssueTrackingCollectionTagsAllResponse$inboundSchema;
  /** @deprecated use `IssueTrackingCollectionTagsAllResponse$outboundSchema` instead. */
  export const outboundSchema =
    IssueTrackingCollectionTagsAllResponse$outboundSchema;
  /** @deprecated use `IssueTrackingCollectionTagsAllResponse$Outbound` instead. */
  export type Outbound = IssueTrackingCollectionTagsAllResponse$Outbound;
}
