/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as components from "../components/index.js";

export type PosLocationsOneGlobals = {
  /**
   * ID of the consumer which you want to get or push data from
   */
  customerId?: string | undefined;
  /**
   * The ID of your Unify application
   */
  appId?: string | undefined;
};

export type PosLocationsOneRequest = {
  /**
   * ID of the record you are acting upon.
   */
  id: string;
  /**
   * Provide the service id you want to call (e.g., pipedrive). Only needed when a consumer has activated multiple integrations for a Unified API.
   */
  serviceId?: string | undefined;
  /**
   * Include raw response. Mostly used for debugging purposes
   */
  raw?: boolean | undefined;
  /**
   * The 'fields' parameter allows API users to specify the fields they want to include in the API response. If this parameter is not present, the API will return all available fields. If this parameter is present, only the fields specified in the comma-separated string will be included in the response. Nested properties can also be requested by using a dot notation. <br /><br />Example: `fields=name,email,addresses.city`<br /><br />In the example above, the response will only include the fields "name", "email" and "addresses.city". If any other fields are available, they will be excluded.
   */
  fields?: string | null | undefined;
};

export type PosLocationsOneResponse =
  | components.GetLocationResponse
  | components.UnexpectedErrorResponse;

/** @internal */
export const PosLocationsOneGlobals$inboundSchema: z.ZodType<
  PosLocationsOneGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  customerId: z.string().optional(),
  appId: z.string().optional(),
});

/** @internal */
export type PosLocationsOneGlobals$Outbound = {
  customerId?: string | undefined;
  appId?: string | undefined;
};

/** @internal */
export const PosLocationsOneGlobals$outboundSchema: z.ZodType<
  PosLocationsOneGlobals$Outbound,
  z.ZodTypeDef,
  PosLocationsOneGlobals
> = z.object({
  customerId: z.string().optional(),
  appId: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PosLocationsOneGlobals$ {
  /** @deprecated use `PosLocationsOneGlobals$inboundSchema` instead. */
  export const inboundSchema = PosLocationsOneGlobals$inboundSchema;
  /** @deprecated use `PosLocationsOneGlobals$outboundSchema` instead. */
  export const outboundSchema = PosLocationsOneGlobals$outboundSchema;
  /** @deprecated use `PosLocationsOneGlobals$Outbound` instead. */
  export type Outbound = PosLocationsOneGlobals$Outbound;
}

/** @internal */
export const PosLocationsOneRequest$inboundSchema: z.ZodType<
  PosLocationsOneRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  serviceId: z.string().optional(),
  raw: z.boolean().default(false),
  fields: z.nullable(z.string()).optional(),
});

/** @internal */
export type PosLocationsOneRequest$Outbound = {
  id: string;
  serviceId?: string | undefined;
  raw: boolean;
  fields?: string | null | undefined;
};

/** @internal */
export const PosLocationsOneRequest$outboundSchema: z.ZodType<
  PosLocationsOneRequest$Outbound,
  z.ZodTypeDef,
  PosLocationsOneRequest
> = z.object({
  id: z.string(),
  serviceId: z.string().optional(),
  raw: z.boolean().default(false),
  fields: z.nullable(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PosLocationsOneRequest$ {
  /** @deprecated use `PosLocationsOneRequest$inboundSchema` instead. */
  export const inboundSchema = PosLocationsOneRequest$inboundSchema;
  /** @deprecated use `PosLocationsOneRequest$outboundSchema` instead. */
  export const outboundSchema = PosLocationsOneRequest$outboundSchema;
  /** @deprecated use `PosLocationsOneRequest$Outbound` instead. */
  export type Outbound = PosLocationsOneRequest$Outbound;
}

/** @internal */
export const PosLocationsOneResponse$inboundSchema: z.ZodType<
  PosLocationsOneResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  components.GetLocationResponse$inboundSchema,
  components.UnexpectedErrorResponse$inboundSchema,
]);

/** @internal */
export type PosLocationsOneResponse$Outbound =
  | components.GetLocationResponse$Outbound
  | components.UnexpectedErrorResponse$Outbound;

/** @internal */
export const PosLocationsOneResponse$outboundSchema: z.ZodType<
  PosLocationsOneResponse$Outbound,
  z.ZodTypeDef,
  PosLocationsOneResponse
> = z.union([
  components.GetLocationResponse$outboundSchema,
  components.UnexpectedErrorResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PosLocationsOneResponse$ {
  /** @deprecated use `PosLocationsOneResponse$inboundSchema` instead. */
  export const inboundSchema = PosLocationsOneResponse$inboundSchema;
  /** @deprecated use `PosLocationsOneResponse$outboundSchema` instead. */
  export const outboundSchema = PosLocationsOneResponse$outboundSchema;
  /** @deprecated use `PosLocationsOneResponse$Outbound` instead. */
  export type Outbound = PosLocationsOneResponse$Outbound;
}
