/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type VaultCustomMappingsAllGlobals = {
  /**
   * ID of the consumer which you want to get or push data from
   */
  customerId?: string | undefined;
  /**
   * The ID of your Unify application
   */
  appId?: string | undefined;
};

export type VaultCustomMappingsAllRequest = {
  /**
   * Unified API
   */
  unifiedApi: string;
  /**
   * Service ID of the resource to return
   */
  serviceId: string;
};

export type VaultCustomMappingsAllResponse =
  | components.GetCustomMappingsResponse
  | components.UnexpectedErrorResponse;

/** @internal */
export const VaultCustomMappingsAllGlobals$inboundSchema: z.ZodType<
  VaultCustomMappingsAllGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  customerId: z.string().optional(),
  appId: z.string().optional(),
});

/** @internal */
export type VaultCustomMappingsAllGlobals$Outbound = {
  customerId?: string | undefined;
  appId?: string | undefined;
};

/** @internal */
export const VaultCustomMappingsAllGlobals$outboundSchema: z.ZodType<
  VaultCustomMappingsAllGlobals$Outbound,
  z.ZodTypeDef,
  VaultCustomMappingsAllGlobals
> = z.object({
  customerId: z.string().optional(),
  appId: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace VaultCustomMappingsAllGlobals$ {
  /** @deprecated use `VaultCustomMappingsAllGlobals$inboundSchema` instead. */
  export const inboundSchema = VaultCustomMappingsAllGlobals$inboundSchema;
  /** @deprecated use `VaultCustomMappingsAllGlobals$outboundSchema` instead. */
  export const outboundSchema = VaultCustomMappingsAllGlobals$outboundSchema;
  /** @deprecated use `VaultCustomMappingsAllGlobals$Outbound` instead. */
  export type Outbound = VaultCustomMappingsAllGlobals$Outbound;
}

/** @internal */
export const VaultCustomMappingsAllRequest$inboundSchema: z.ZodType<
  VaultCustomMappingsAllRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  unified_api: z.string(),
  service_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "unified_api": "unifiedApi",
    "service_id": "serviceId",
  });
});

/** @internal */
export type VaultCustomMappingsAllRequest$Outbound = {
  unified_api: string;
  service_id: string;
};

/** @internal */
export const VaultCustomMappingsAllRequest$outboundSchema: z.ZodType<
  VaultCustomMappingsAllRequest$Outbound,
  z.ZodTypeDef,
  VaultCustomMappingsAllRequest
> = z.object({
  unifiedApi: z.string(),
  serviceId: z.string(),
}).transform((v) => {
  return remap$(v, {
    unifiedApi: "unified_api",
    serviceId: "service_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace VaultCustomMappingsAllRequest$ {
  /** @deprecated use `VaultCustomMappingsAllRequest$inboundSchema` instead. */
  export const inboundSchema = VaultCustomMappingsAllRequest$inboundSchema;
  /** @deprecated use `VaultCustomMappingsAllRequest$outboundSchema` instead. */
  export const outboundSchema = VaultCustomMappingsAllRequest$outboundSchema;
  /** @deprecated use `VaultCustomMappingsAllRequest$Outbound` instead. */
  export type Outbound = VaultCustomMappingsAllRequest$Outbound;
}

/** @internal */
export const VaultCustomMappingsAllResponse$inboundSchema: z.ZodType<
  VaultCustomMappingsAllResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  components.GetCustomMappingsResponse$inboundSchema,
  components.UnexpectedErrorResponse$inboundSchema,
]);

/** @internal */
export type VaultCustomMappingsAllResponse$Outbound =
  | components.GetCustomMappingsResponse$Outbound
  | components.UnexpectedErrorResponse$Outbound;

/** @internal */
export const VaultCustomMappingsAllResponse$outboundSchema: z.ZodType<
  VaultCustomMappingsAllResponse$Outbound,
  z.ZodTypeDef,
  VaultCustomMappingsAllResponse
> = z.union([
  components.GetCustomMappingsResponse$outboundSchema,
  components.UnexpectedErrorResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace VaultCustomMappingsAllResponse$ {
  /** @deprecated use `VaultCustomMappingsAllResponse$inboundSchema` instead. */
  export const inboundSchema = VaultCustomMappingsAllResponse$inboundSchema;
  /** @deprecated use `VaultCustomMappingsAllResponse$outboundSchema` instead. */
  export const outboundSchema = VaultCustomMappingsAllResponse$outboundSchema;
  /** @deprecated use `VaultCustomMappingsAllResponse$Outbound` instead. */
  export type Outbound = VaultCustomMappingsAllResponse$Outbound;
}
