// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AccountingDepartmentsFilter struct {
	// Id of the subsidiary to search for
	Subsidiary *string `queryParam:"name=subsidiary"`
}

func (o *AccountingDepartmentsFilter) GetSubsidiary() *string {
	if o == nil {
		return nil
	}
	return o.Subsidiary
}
