// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LinkedResource struct {
	// ID of the resource, typically a lowercased version of name.
	ID *string `json:"id,omitempty"`
	// Name of the property in our Unified API.
	UnifiedProperty *string `json:"unified_property,omitempty"`
}

func (o *LinkedResource) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *LinkedResource) GetUnifiedProperty() *string {
	if o == nil {
		return nil
	}
	return o.UnifiedProperty
}

// JSON Schema of the resource in our Unified API
type Schema struct {
}

type APIResource struct {
	// ID of the resource, typically a lowercased version of name.
	ID *string `json:"id,omitempty"`
	// Name of the resource (plural)
	Name *string `json:"name,omitempty"`
	// Status of the resource. Resources with status live or beta are callable.
	Status *ResourceStatus `json:"status,omitempty"`
	// List of linked resources.
	LinkedResources []LinkedResource `json:"linked_resources,omitempty"`
	// JSON Schema of the resource in our Unified API
	Schema *Schema `json:"schema,omitempty"`
}

func (o *APIResource) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *APIResource) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *APIResource) GetStatus() *ResourceStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *APIResource) GetLinkedResources() []LinkedResource {
	if o == nil {
		return nil
	}
	return o.LinkedResources
}

func (o *APIResource) GetSchema() *Schema {
	if o == nil {
		return nil
	}
	return o.Schema
}
