// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Assignee struct {
	// A unique identifier for an object.
	ID       string  `json:"id"`
	Username *string `json:"username,omitempty"`
}

func (o *Assignee) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *Assignee) GetUsername() *string {
	if o == nil {
		return nil
	}
	return o.Username
}
