// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PeriodType - The type of period to include in the resource: month, quarter, year.
type PeriodType string

const (
	PeriodTypeMonth   PeriodType = "month"
	PeriodTypeQuarter PeriodType = "quarter"
	PeriodTypeYear    PeriodType = "year"
)

func (e PeriodType) ToPointer() *PeriodType {
	return &e
}

// BalanceSheetFilterAccountingMethod - The accounting method used for the report: cash or accrual.
type BalanceSheetFilterAccountingMethod string

const (
	BalanceSheetFilterAccountingMethodCash    BalanceSheetFilterAccountingMethod = "cash"
	BalanceSheetFilterAccountingMethodAccrual BalanceSheetFilterAccountingMethod = "accrual"
)

func (e BalanceSheetFilterAccountingMethod) ToPointer() *BalanceSheetFilterAccountingMethod {
	return &e
}

type BalanceSheetFilter struct {
	// The start date of the period to include in the resource.
	//
	// Deprecated: This field is deprecated and may be removed in a future version..
	StartDate *string `queryParam:"name=start_date"`
	// The end date of the period to include in the resource.
	EndDate *string `queryParam:"name=end_date"`
	// The number of periods to include in the resource.
	PeriodCount *int64 `queryParam:"name=period_count"`
	// The type of period to include in the resource: month, quarter, year.
	PeriodType *PeriodType `queryParam:"name=period_type"`
	// The ID of the location to include in the resource.
	LocationID *string `queryParam:"name=location_id"`
	// The accounting method used for the report: cash or accrual.
	AccountingMethod *BalanceSheetFilterAccountingMethod `queryParam:"name=accounting_method"`
}

func (o *BalanceSheetFilter) GetStartDate() *string {
	if o == nil {
		return nil
	}
	return o.StartDate
}

func (o *BalanceSheetFilter) GetEndDate() *string {
	if o == nil {
		return nil
	}
	return o.EndDate
}

func (o *BalanceSheetFilter) GetPeriodCount() *int64 {
	if o == nil {
		return nil
	}
	return o.PeriodCount
}

func (o *BalanceSheetFilter) GetPeriodType() *PeriodType {
	if o == nil {
		return nil
	}
	return o.PeriodType
}

func (o *BalanceSheetFilter) GetLocationID() *string {
	if o == nil {
		return nil
	}
	return o.LocationID
}

func (o *BalanceSheetFilter) GetAccountingMethod() *BalanceSheetFilterAccountingMethod {
	if o == nil {
		return nil
	}
	return o.AccountingMethod
}
