// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// BatchSupportMode - The connector's overall batch capability: `none` when no resource supports a batch write, otherwise the mode most of its resources use. This is a summary — read `resources` for the answer that applies to the resource you are calling, because a connector can be `native` for one resource and `loop` for another.
type BatchSupportMode string

const (
	BatchSupportModeNone   BatchSupportMode = "none"
	BatchSupportModeNative BatchSupportMode = "native"
	BatchSupportModeLoop   BatchSupportMode = "loop"
)

func (e BatchSupportMode) ToPointer() *BatchSupportMode {
	return &e
}

// ResourcesMode - `none` means this resource refuses batch writes. `native` satisfies a batch in a single downstream call against the provider's own batch endpoint, so the request counts as one request against your plan. `loop` satisfies it as a bounded sequential fan-out, one downstream call per item — so a request of N records takes roughly N times as long and counts as N requests.
type ResourcesMode string

const (
	ResourcesModeNone   ResourcesMode = "none"
	ResourcesModeNative ResourcesMode = "native"
	ResourcesModeLoop   ResourcesMode = "loop"
)

func (e ResourcesMode) ToPointer() *ResourcesMode {
	return &e
}

type BatchSupportResources struct {
	// `none` means this resource refuses batch writes. `native` satisfies a batch in a single downstream call against the provider's own batch endpoint, so the request counts as one request against your plan. `loop` satisfies it as a bounded sequential fan-out, one downstream call per item — so a request of N records takes roughly N times as long and counts as N requests.
	Mode ResourcesMode `json:"mode"`
	// The maximum number of items this resource accepts in one request. A request carrying more is rejected before any record is written. Resources on the same connector can differ: a resource that writes records one at a time is usually capped lower than one that writes them in a single call. Absent when the connector has not declared one, in which case the platform default applies.
	MaxItems *int64 `json:"max_items,omitempty"`
}

func (o *BatchSupportResources) GetMode() ResourcesMode {
	if o == nil {
		return ResourcesMode("")
	}
	return o.Mode
}

func (o *BatchSupportResources) GetMaxItems() *int64 {
	if o == nil {
		return nil
	}
	return o.MaxItems
}

// BatchSupport - How this connector satisfies a batch write, per resource. Read this before calling a batch endpoint: support, execution mode and the per-request limit all vary by resource on the same connector, and the mode determines both latency and how many requests the call counts against your plan.
type BatchSupport struct {
	// The connector's overall batch capability: `none` when no resource supports a batch write, otherwise the mode most of its resources use. This is a summary — read `resources` for the answer that applies to the resource you are calling, because a connector can be `native` for one resource and `loop` for another.
	Mode BatchSupportMode `json:"mode"`
	// Batch support for each resource that has a batch endpoint, keyed by the batch resource name (for example `invoices-batch`). A resource absent from this map, or reporting `none`, will refuse a batch request with a 501.
	Resources map[string]BatchSupportResources `json:"resources,omitempty"`
}

func (o *BatchSupport) GetMode() BatchSupportMode {
	if o == nil {
		return BatchSupportMode("")
	}
	return o.Mode
}

func (o *BatchSupport) GetResources() map[string]BatchSupportResources {
	if o == nil {
		return nil
	}
	return o.Resources
}
