// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type BatchTrackingCategoriesRequestItem struct {
	// A caller-supplied reference for this item, echoed back on the matching result so each outcome can be tied to the record it came from. Must be unique within the request. Never sent to the connector.
	Ref *string `json:"_ref,omitempty"`
	// The writable shape of TrackingCategory for a batch create. Identical to [TrackingCategory](the model returned on reads) with the read-only properties removed — the same properties the single-record create endpoint rejects, so a batched record and a single-record create accept exactly the same body.
	Data TrackingCategoryCreateInput `json:"data"`
}

func (o *BatchTrackingCategoriesRequestItem) GetRef() *string {
	if o == nil {
		return nil
	}
	return o.Ref
}

func (o *BatchTrackingCategoriesRequestItem) GetData() TrackingCategoryCreateInput {
	if o == nil {
		return TrackingCategoryCreateInput{}
	}
	return o.Data
}

// BatchTrackingCategoriesRequest - A batch of tracking categories to write in a single request. Each item is processed independently: some may succeed while others fail, and the response carries one result per item in the order they were sent.
type BatchTrackingCategoriesRequest struct {
	// The records to write. The per-connector limit is the real cap and is usually lower than the ceiling here: read `batch_support.resources[<resource>].max_items` on the Connector API for the connector you are calling, or the resource gotchas. This ceiling exists so an oversized array is rejected by request validation before any per-item work runs, rather than after it.
	Items []BatchTrackingCategoriesRequestItem `json:"items"`
}

func (o *BatchTrackingCategoriesRequest) GetItems() []BatchTrackingCategoriesRequestItem {
	if o == nil {
		return []BatchTrackingCategoriesRequestItem{}
	}
	return o.Items
}
