// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/optionalnullable"
)

// GetPayrollResponse - Payrolls
type GetPayrollResponse struct {
	// HTTP Response Status Code
	StatusCode int64 `json:"status_code"`
	// HTTP Response Status
	Status string `json:"status"`
	// Apideck ID of service provider
	Service string `json:"service"`
	// Unified API resource name
	Resource string `json:"resource"`
	// Operation performed
	Operation string  `json:"operation"`
	Data      Payroll `json:"data"`
	// Raw response from the integration when raw=true query param is provided
	Raw optionalnullable.OptionalNullable[map[string]any] `json:"_raw,omitempty"`
}

func (o *GetPayrollResponse) GetStatusCode() int64 {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetPayrollResponse) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

func (o *GetPayrollResponse) GetService() string {
	if o == nil {
		return ""
	}
	return o.Service
}

func (o *GetPayrollResponse) GetResource() string {
	if o == nil {
		return ""
	}
	return o.Resource
}

func (o *GetPayrollResponse) GetOperation() string {
	if o == nil {
		return ""
	}
	return o.Operation
}

func (o *GetPayrollResponse) GetData() Payroll {
	if o == nil {
		return Payroll{}
	}
	return o.Data
}

func (o *GetPayrollResponse) GetRaw() optionalnullable.OptionalNullable[map[string]any] {
	if o == nil {
		return nil
	}
	return o.Raw
}
