// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// GetSubsidiariesResponse - Subsidiaries
type GetSubsidiariesResponse struct {
	// HTTP Response Status Code
	StatusCode int64 `json:"status_code"`
	// HTTP Response Status
	Status string `json:"status"`
	// Apideck ID of service provider
	Service string `json:"service"`
	// Unified API resource name
	Resource string `json:"resource"`
	// Operation performed
	Operation string       `json:"operation"`
	Data      []Subsidiary `json:"data"`
	// Response metadata
	Meta *Meta `json:"meta,omitempty"`
	// Links to navigate to previous or next pages through the API
	Links *Links `json:"links,omitempty"`
	// Raw response from the integration when raw=true query param is provided
	Raw map[string]any `json:"_raw,omitempty"`
}

func (o *GetSubsidiariesResponse) GetStatusCode() int64 {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetSubsidiariesResponse) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

func (o *GetSubsidiariesResponse) GetService() string {
	if o == nil {
		return ""
	}
	return o.Service
}

func (o *GetSubsidiariesResponse) GetResource() string {
	if o == nil {
		return ""
	}
	return o.Resource
}

func (o *GetSubsidiariesResponse) GetOperation() string {
	if o == nil {
		return ""
	}
	return o.Operation
}

func (o *GetSubsidiariesResponse) GetData() []Subsidiary {
	if o == nil {
		return []Subsidiary{}
	}
	return o.Data
}

func (o *GetSubsidiariesResponse) GetMeta() *Meta {
	if o == nil {
		return nil
	}
	return o.Meta
}

func (o *GetSubsidiariesResponse) GetLinks() *Links {
	if o == nil {
		return nil
	}
	return o.Links
}

func (o *GetSubsidiariesResponse) GetRaw() map[string]any {
	if o == nil {
		return nil
	}
	return o.Raw
}
