// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/optionalnullable"
)

// LinkedEcommerceCustomer - The customer this entity is linked to.
type LinkedEcommerceCustomer struct {
	// The ID of the customer this entity is linked to.
	ID optionalnullable.OptionalNullable[string] `json:"id,omitempty"`
	// Full name of the customer
	Name optionalnullable.OptionalNullable[string] `json:"name,omitempty"`
	// First name of the customer
	FirstName optionalnullable.OptionalNullable[string] `json:"first_name,omitempty"`
	// Last name of the customer
	LastName optionalnullable.OptionalNullable[string] `json:"last_name,omitempty"`
	// Company name of the customer
	CompanyName  optionalnullable.OptionalNullable[string]        `json:"company_name,omitempty"`
	PhoneNumbers optionalnullable.OptionalNullable[[]PhoneNumber] `json:"phone_numbers,omitempty"`
	Emails       optionalnullable.OptionalNullable[[]Email]       `json:"emails,omitempty"`
}

func (o *LinkedEcommerceCustomer) GetID() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *LinkedEcommerceCustomer) GetName() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *LinkedEcommerceCustomer) GetFirstName() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.FirstName
}

func (o *LinkedEcommerceCustomer) GetLastName() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.LastName
}

func (o *LinkedEcommerceCustomer) GetCompanyName() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.CompanyName
}

func (o *LinkedEcommerceCustomer) GetPhoneNumbers() optionalnullable.OptionalNullable[[]PhoneNumber] {
	if o == nil {
		return nil
	}
	return o.PhoneNumbers
}

func (o *LinkedEcommerceCustomer) GetEmails() optionalnullable.OptionalNullable[[]Email] {
	if o == nil {
		return nil
	}
	return o.Emails
}
