// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/optionalnullable"
	"mockserver/internal/sdk/utils"
	"time"
)

// TicketPriority - Priority of the ticket
type TicketPriority string

const (
	TicketPriorityLow    TicketPriority = "low"
	TicketPriorityNormal TicketPriority = "normal"
	TicketPriorityHigh   TicketPriority = "high"
	TicketPriorityUrgent TicketPriority = "urgent"
)

func (e TicketPriority) ToPointer() *TicketPriority {
	return &e
}

type Ticket struct {
	// A unique identifier for an object.
	ID string `json:"id"`
	// The ticket's parent ID
	ParentID optionalnullable.OptionalNullable[string] `json:"parent_id,omitempty"`
	// The ticket's collection ID
	CollectionID optionalnullable.OptionalNullable[string] `json:"collection_id,omitempty"`
	// The ticket's type
	Type optionalnullable.OptionalNullable[string] `json:"type,omitempty"`
	// Subject of the ticket
	Subject optionalnullable.OptionalNullable[string] `json:"subject,omitempty"`
	// The ticket's description. HTML version of description is mapped if supported by the third-party platform
	Description optionalnullable.OptionalNullable[string] `json:"description,omitempty"`
	// The current status of the ticket. Possible values include: open, in_progress, closed, or - in cases where there is no clear mapping - the original value passed through.
	Status optionalnullable.OptionalNullable[string] `json:"status,omitempty"`
	// Priority of the ticket
	Priority  optionalnullable.OptionalNullable[TicketPriority] `json:"priority,omitempty"`
	Assignees []Assignee                                        `json:"assignees,omitempty"`
	// The date and time when the object was last updated.
	UpdatedAt optionalnullable.OptionalNullable[time.Time] `json:"updated_at,omitempty"`
	// The date and time when the object was created.
	CreatedAt optionalnullable.OptionalNullable[time.Time] `json:"created_at,omitempty"`
	// The user who created the object.
	CreatedBy optionalnullable.OptionalNullable[string] `json:"created_by,omitempty"`
	// Due date of the ticket
	DueDate optionalnullable.OptionalNullable[time.Time] `json:"due_date,omitempty"`
	// When the ticket was completed
	CompletedAt optionalnullable.OptionalNullable[time.Time] `json:"completed_at,omitempty"`
	Tags        []CollectionTag                              `json:"tags,omitempty"`
	// When custom mappings are configured on the resource, the result is included here.
	CustomMappings optionalnullable.OptionalNullable[map[string]any] `json:"custom_mappings,omitempty"`
	// The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources.
	PassThrough []PassThroughBody `json:"pass_through,omitempty"`
}

func (t Ticket) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *Ticket) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, []string{"id"}); err != nil {
		return err
	}
	return nil
}

func (o *Ticket) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *Ticket) GetParentID() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.ParentID
}

func (o *Ticket) GetCollectionID() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.CollectionID
}

func (o *Ticket) GetType() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *Ticket) GetSubject() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Subject
}

func (o *Ticket) GetDescription() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *Ticket) GetStatus() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *Ticket) GetPriority() optionalnullable.OptionalNullable[TicketPriority] {
	if o == nil {
		return nil
	}
	return o.Priority
}

func (o *Ticket) GetAssignees() []Assignee {
	if o == nil {
		return nil
	}
	return o.Assignees
}

func (o *Ticket) GetUpdatedAt() optionalnullable.OptionalNullable[time.Time] {
	if o == nil {
		return nil
	}
	return o.UpdatedAt
}

func (o *Ticket) GetCreatedAt() optionalnullable.OptionalNullable[time.Time] {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *Ticket) GetCreatedBy() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.CreatedBy
}

func (o *Ticket) GetDueDate() optionalnullable.OptionalNullable[time.Time] {
	if o == nil {
		return nil
	}
	return o.DueDate
}

func (o *Ticket) GetCompletedAt() optionalnullable.OptionalNullable[time.Time] {
	if o == nil {
		return nil
	}
	return o.CompletedAt
}

func (o *Ticket) GetTags() []CollectionTag {
	if o == nil {
		return nil
	}
	return o.Tags
}

func (o *Ticket) GetCustomMappings() optionalnullable.OptionalNullable[map[string]any] {
	if o == nil {
		return nil
	}
	return o.CustomMappings
}

func (o *Ticket) GetPassThrough() []PassThroughBody {
	if o == nil {
		return nil
	}
	return o.PassThrough
}

type TicketInput struct {
	// The ticket's parent ID
	ParentID optionalnullable.OptionalNullable[string] `json:"parent_id,omitempty"`
	// The ticket's type
	Type optionalnullable.OptionalNullable[string] `json:"type,omitempty"`
	// Subject of the ticket
	Subject optionalnullable.OptionalNullable[string] `json:"subject,omitempty"`
	// The ticket's description. HTML version of description is mapped if supported by the third-party platform
	Description optionalnullable.OptionalNullable[string] `json:"description,omitempty"`
	// The current status of the ticket. Possible values include: open, in_progress, closed, or - in cases where there is no clear mapping - the original value passed through.
	Status optionalnullable.OptionalNullable[string] `json:"status,omitempty"`
	// Priority of the ticket
	Priority  optionalnullable.OptionalNullable[TicketPriority] `json:"priority,omitempty"`
	Assignees []AssigneeInput                                   `json:"assignees,omitempty"`
	// Due date of the ticket
	DueDate optionalnullable.OptionalNullable[time.Time] `json:"due_date,omitempty"`
	Tags    []CollectionTagInput                         `json:"tags,omitempty"`
	// The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources.
	PassThrough []PassThroughBody `json:"pass_through,omitempty"`
}

func (t TicketInput) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TicketInput) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *TicketInput) GetParentID() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.ParentID
}

func (o *TicketInput) GetType() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *TicketInput) GetSubject() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Subject
}

func (o *TicketInput) GetDescription() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *TicketInput) GetStatus() optionalnullable.OptionalNullable[string] {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *TicketInput) GetPriority() optionalnullable.OptionalNullable[TicketPriority] {
	if o == nil {
		return nil
	}
	return o.Priority
}

func (o *TicketInput) GetAssignees() []AssigneeInput {
	if o == nil {
		return nil
	}
	return o.Assignees
}

func (o *TicketInput) GetDueDate() optionalnullable.OptionalNullable[time.Time] {
	if o == nil {
		return nil
	}
	return o.DueDate
}

func (o *TicketInput) GetTags() []CollectionTagInput {
	if o == nil {
		return nil
	}
	return o.Tags
}

func (o *TicketInput) GetPassThrough() []PassThroughBody {
	if o == nil {
		return nil
	}
	return o.PassThrough
}
