// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// UnifiedAPIID - Name of Apideck Unified API
type UnifiedAPIID string

const (
	UnifiedAPIIDAccounting         UnifiedAPIID = "accounting"
	UnifiedAPIIDAts                UnifiedAPIID = "ats"
	UnifiedAPIIDCalendar           UnifiedAPIID = "calendar"
	UnifiedAPIIDCrm                UnifiedAPIID = "crm"
	UnifiedAPIIDCsp                UnifiedAPIID = "csp"
	UnifiedAPIIDCustomerSupport    UnifiedAPIID = "customer-support"
	UnifiedAPIIDEcommerce          UnifiedAPIID = "ecommerce"
	UnifiedAPIIDEmail              UnifiedAPIID = "email"
	UnifiedAPIIDEmailMarketing     UnifiedAPIID = "email-marketing"
	UnifiedAPIIDExpenseManagement  UnifiedAPIID = "expense-management"
	UnifiedAPIIDFileStorage        UnifiedAPIID = "file-storage"
	UnifiedAPIIDForm               UnifiedAPIID = "form"
	UnifiedAPIIDHris               UnifiedAPIID = "hris"
	UnifiedAPIIDLead               UnifiedAPIID = "lead"
	UnifiedAPIIDPayroll            UnifiedAPIID = "payroll"
	UnifiedAPIIDPos                UnifiedAPIID = "pos"
	UnifiedAPIIDProcurement        UnifiedAPIID = "procurement"
	UnifiedAPIIDProjectManagement  UnifiedAPIID = "project-management"
	UnifiedAPIIDScript             UnifiedAPIID = "script"
	UnifiedAPIIDSms                UnifiedAPIID = "sms"
	UnifiedAPIIDSpreadsheet        UnifiedAPIID = "spreadsheet"
	UnifiedAPIIDTeamMessaging      UnifiedAPIID = "team-messaging"
	UnifiedAPIIDIssueTracking      UnifiedAPIID = "issue-tracking"
	UnifiedAPIIDTimeRegistration   UnifiedAPIID = "time-registration"
	UnifiedAPIIDTransactionalEmail UnifiedAPIID = "transactional-email"
	UnifiedAPIIDVault              UnifiedAPIID = "vault"
	UnifiedAPIIDDataWarehouse      UnifiedAPIID = "data-warehouse"
)

func (e UnifiedAPIID) ToPointer() *UnifiedAPIID {
	return &e
}
