/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  CustomerCreateInput,
  CustomerCreateInput$Outbound,
  CustomerCreateInput$outboundSchema,
} from "./customercreateinput.js";

export type BatchCustomersRequestItems = {
  /**
   * A caller-supplied reference for this item, echoed back on the matching result so each outcome can be tied to the record it came from. Must be unique within the request. Never sent to the connector.
   */
  ref?: string | undefined;
  /**
   * The writable shape of Customer for a batch create. Identical to [Customer](the model returned on reads) with the read-only properties removed — the same properties the single-record create endpoint rejects, so a batched record and a single-record create accept exactly the same body.
   */
  data: CustomerCreateInput;
};

/**
 * A batch of customers to write in a single request. Each item is processed independently: some may succeed while others fail, and the response carries one result per item in the order they were sent.
 */
export type BatchCustomersRequest = {
  /**
   * The records to write. The per-connector limit is the real cap and is usually lower than the ceiling here: read `batch_support.resources[<resource>].max_items` on the Connector API for the connector you are calling, or the resource gotchas. This ceiling exists so an oversized array is rejected by request validation before any per-item work runs, rather than after it.
   */
  items: Array<BatchCustomersRequestItems>;
};

/** @internal */
export type BatchCustomersRequestItems$Outbound = {
  _ref?: string | undefined;
  data: CustomerCreateInput$Outbound;
};

/** @internal */
export const BatchCustomersRequestItems$outboundSchema: z.ZodType<
  BatchCustomersRequestItems$Outbound,
  z.ZodTypeDef,
  BatchCustomersRequestItems
> = z.object({
  ref: z.string().optional(),
  data: CustomerCreateInput$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    ref: "_ref",
  });
});

export function batchCustomersRequestItemsToJSON(
  batchCustomersRequestItems: BatchCustomersRequestItems,
): string {
  return JSON.stringify(
    BatchCustomersRequestItems$outboundSchema.parse(batchCustomersRequestItems),
  );
}

/** @internal */
export type BatchCustomersRequest$Outbound = {
  items: Array<BatchCustomersRequestItems$Outbound>;
};

/** @internal */
export const BatchCustomersRequest$outboundSchema: z.ZodType<
  BatchCustomersRequest$Outbound,
  z.ZodTypeDef,
  BatchCustomersRequest
> = z.object({
  items: z.array(z.lazy(() => BatchCustomersRequestItems$outboundSchema)),
});

export function batchCustomersRequestToJSON(
  batchCustomersRequest: BatchCustomersRequest,
): string {
  return JSON.stringify(
    BatchCustomersRequest$outboundSchema.parse(batchCustomersRequest),
  );
}
