/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Filter by bill status
 */
export const BillsFilterStatus = {
  Paid: "paid",
  Unpaid: "unpaid",
  PartiallyPaid: "partially_paid",
} as const;
/**
 * Filter by bill status
 */
export type BillsFilterStatus = ClosedEnum<typeof BillsFilterStatus>;

export type BillsFilter = {
  updatedSince?: Date | undefined;
  /**
   * Filter by bill status
   */
  status?: BillsFilterStatus | undefined;
};

/** @internal */
export const BillsFilterStatus$outboundSchema: z.ZodNativeEnum<
  typeof BillsFilterStatus
> = z.nativeEnum(BillsFilterStatus);

/** @internal */
export type BillsFilter$Outbound = {
  updated_since?: string | undefined;
  status?: string | undefined;
};

/** @internal */
export const BillsFilter$outboundSchema: z.ZodType<
  BillsFilter$Outbound,
  z.ZodTypeDef,
  BillsFilter
> = z.object({
  updatedSince: z.date().transform(v => v.toISOString()).optional(),
  status: BillsFilterStatus$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    updatedSince: "updated_since",
  });
});

export function billsFilterToJSON(billsFilter: BillsFilter): string {
  return JSON.stringify(BillsFilter$outboundSchema.parse(billsFilter));
}
