/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

export const ExpensesFilterStatus = {
  Draft: "draft",
  PendingApproval: "pending_approval",
  Approved: "approved",
  Posted: "posted",
  Voided: "voided",
  Rejected: "rejected",
  Deleted: "deleted",
  Other: "other",
} as const;
export type ExpensesFilterStatus = ClosedEnum<typeof ExpensesFilterStatus>;

export const ExpensesFilterType = {
  Expense: "expense",
  Refund: "refund",
} as const;
export type ExpensesFilterType = ClosedEnum<typeof ExpensesFilterType>;

export type ExpensesFilter = {
  updatedSince?: Date | undefined;
  status?: ExpensesFilterStatus | undefined;
  type?: ExpensesFilterType | undefined;
};

/** @internal */
export const ExpensesFilterStatus$outboundSchema: z.ZodNativeEnum<
  typeof ExpensesFilterStatus
> = z.nativeEnum(ExpensesFilterStatus);

/** @internal */
export const ExpensesFilterType$outboundSchema: z.ZodNativeEnum<
  typeof ExpensesFilterType
> = z.nativeEnum(ExpensesFilterType);

/** @internal */
export type ExpensesFilter$Outbound = {
  updated_since?: string | undefined;
  status?: string | undefined;
  type?: string | undefined;
};

/** @internal */
export const ExpensesFilter$outboundSchema: z.ZodType<
  ExpensesFilter$Outbound,
  z.ZodTypeDef,
  ExpensesFilter
> = z.object({
  updatedSince: z.date().transform(v => v.toISOString()).optional(),
  status: ExpensesFilterStatus$outboundSchema.optional(),
  type: ExpensesFilterType$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    updatedSince: "updated_since",
  });
});

export function expensesFilterToJSON(expensesFilter: ExpensesFilter): string {
  return JSON.stringify(ExpensesFilter$outboundSchema.parse(expensesFilter));
}
