/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AgedDebtors,
  AgedDebtors$inboundSchema,
  AgedDebtors$Outbound,
  AgedDebtors$outboundSchema,
} from "./ageddebtors.js";

/**
 * Aged Debtors
 */
export type GetAgedDebtorsResponse = {
  /**
   * HTTP Response Status Code
   */
  statusCode: number;
  /**
   * HTTP Response Status
   */
  status: string;
  /**
   * Apideck ID of service provider
   */
  service: string;
  /**
   * Unified API resource name
   */
  resource: string;
  /**
   * Operation performed
   */
  operation: string;
  data: AgedDebtors;
};

/** @internal */
export const GetAgedDebtorsResponse$inboundSchema: z.ZodType<
  GetAgedDebtorsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  status_code: z.number().int(),
  status: z.string(),
  service: z.string(),
  resource: z.string(),
  operation: z.string(),
  data: AgedDebtors$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "status_code": "statusCode",
  });
});

/** @internal */
export type GetAgedDebtorsResponse$Outbound = {
  status_code: number;
  status: string;
  service: string;
  resource: string;
  operation: string;
  data: AgedDebtors$Outbound;
};

/** @internal */
export const GetAgedDebtorsResponse$outboundSchema: z.ZodType<
  GetAgedDebtorsResponse$Outbound,
  z.ZodTypeDef,
  GetAgedDebtorsResponse
> = z.object({
  statusCode: z.number().int(),
  status: z.string(),
  service: z.string(),
  resource: z.string(),
  operation: z.string(),
  data: AgedDebtors$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    statusCode: "status_code",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAgedDebtorsResponse$ {
  /** @deprecated use `GetAgedDebtorsResponse$inboundSchema` instead. */
  export const inboundSchema = GetAgedDebtorsResponse$inboundSchema;
  /** @deprecated use `GetAgedDebtorsResponse$outboundSchema` instead. */
  export const outboundSchema = GetAgedDebtorsResponse$outboundSchema;
  /** @deprecated use `GetAgedDebtorsResponse$Outbound` instead. */
  export type Outbound = GetAgedDebtorsResponse$Outbound;
}

export function getAgedDebtorsResponseToJSON(
  getAgedDebtorsResponse: GetAgedDebtorsResponse,
): string {
  return JSON.stringify(
    GetAgedDebtorsResponse$outboundSchema.parse(getAgedDebtorsResponse),
  );
}

export function getAgedDebtorsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetAgedDebtorsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAgedDebtorsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAgedDebtorsResponse' from JSON`,
  );
}
