/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  Bill,
  Bill$inboundSchema,
  Bill$Outbound,
  Bill$outboundSchema,
} from "./billinput.js";

/**
 * Bill
 */
export type GetBillResponse = {
  /**
   * HTTP Response Status Code
   */
  statusCode: number;
  /**
   * HTTP Response Status
   */
  status: string;
  /**
   * Apideck ID of service provider
   */
  service: string;
  /**
   * Unified API resource name
   */
  resource: string;
  /**
   * Operation performed
   */
  operation: string;
  data: Bill;
  /**
   * Raw response from the integration when raw=true query param is provided
   */
  raw?: { [k: string]: any } | null | undefined;
};

/** @internal */
export const GetBillResponse$inboundSchema: z.ZodType<
  GetBillResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  status_code: z.number().int(),
  status: z.string(),
  service: z.string(),
  resource: z.string(),
  operation: z.string(),
  data: Bill$inboundSchema,
  _raw: z.nullable(z.record(z.any())).optional(),
}).transform((v) => {
  return remap$(v, {
    "status_code": "statusCode",
    "_raw": "raw",
  });
});

/** @internal */
export type GetBillResponse$Outbound = {
  status_code: number;
  status: string;
  service: string;
  resource: string;
  operation: string;
  data: Bill$Outbound;
  _raw?: { [k: string]: any } | null | undefined;
};

/** @internal */
export const GetBillResponse$outboundSchema: z.ZodType<
  GetBillResponse$Outbound,
  z.ZodTypeDef,
  GetBillResponse
> = z.object({
  statusCode: z.number().int(),
  status: z.string(),
  service: z.string(),
  resource: z.string(),
  operation: z.string(),
  data: Bill$outboundSchema,
  raw: z.nullable(z.record(z.any())).optional(),
}).transform((v) => {
  return remap$(v, {
    statusCode: "status_code",
    raw: "_raw",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetBillResponse$ {
  /** @deprecated use `GetBillResponse$inboundSchema` instead. */
  export const inboundSchema = GetBillResponse$inboundSchema;
  /** @deprecated use `GetBillResponse$outboundSchema` instead. */
  export const outboundSchema = GetBillResponse$outboundSchema;
  /** @deprecated use `GetBillResponse$Outbound` instead. */
  export type Outbound = GetBillResponse$Outbound;
}

export function getBillResponseToJSON(
  getBillResponse: GetBillResponse,
): string {
  return JSON.stringify(GetBillResponse$outboundSchema.parse(getBillResponse));
}

export function getBillResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetBillResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBillResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBillResponse' from JSON`,
  );
}
