/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  Location,
  Location$inboundSchema,
  Location$Outbound,
  Location$outboundSchema,
} from "./location.js";

/**
 * Locations
 */
export type GetLocationResponse = {
  /**
   * HTTP Response Status Code
   */
  statusCode: number;
  /**
   * HTTP Response Status
   */
  status: string;
  /**
   * Apideck ID of service provider
   */
  service: string;
  /**
   * Unified API resource name
   */
  resource: string;
  /**
   * Operation performed
   */
  operation: string;
  data: Location;
};

/** @internal */
export const GetLocationResponse$inboundSchema: z.ZodType<
  GetLocationResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  status_code: z.number().int(),
  status: z.string(),
  service: z.string(),
  resource: z.string(),
  operation: z.string(),
  data: Location$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "status_code": "statusCode",
  });
});

/** @internal */
export type GetLocationResponse$Outbound = {
  status_code: number;
  status: string;
  service: string;
  resource: string;
  operation: string;
  data: Location$Outbound;
};

/** @internal */
export const GetLocationResponse$outboundSchema: z.ZodType<
  GetLocationResponse$Outbound,
  z.ZodTypeDef,
  GetLocationResponse
> = z.object({
  statusCode: z.number().int(),
  status: z.string(),
  service: z.string(),
  resource: z.string(),
  operation: z.string(),
  data: Location$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    statusCode: "status_code",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetLocationResponse$ {
  /** @deprecated use `GetLocationResponse$inboundSchema` instead. */
  export const inboundSchema = GetLocationResponse$inboundSchema;
  /** @deprecated use `GetLocationResponse$outboundSchema` instead. */
  export const outboundSchema = GetLocationResponse$outboundSchema;
  /** @deprecated use `GetLocationResponse$Outbound` instead. */
  export type Outbound = GetLocationResponse$Outbound;
}
