/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  PurchaseOrder,
  PurchaseOrder$inboundSchema,
  PurchaseOrder$Outbound,
  PurchaseOrder$outboundSchema,
} from "./purchaseorder.js";

/**
 * PurchaseOrders
 */
export type GetPurchaseOrderResponse = {
  /**
   * HTTP Response Status Code
   */
  statusCode: number;
  /**
   * HTTP Response Status
   */
  status: string;
  /**
   * Apideck ID of service provider
   */
  service: string;
  /**
   * Unified API resource name
   */
  resource: string;
  /**
   * Operation performed
   */
  operation: string;
  data: PurchaseOrder;
};

/** @internal */
export const GetPurchaseOrderResponse$inboundSchema: z.ZodType<
  GetPurchaseOrderResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  status_code: z.number().int(),
  status: z.string(),
  service: z.string(),
  resource: z.string(),
  operation: z.string(),
  data: PurchaseOrder$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "status_code": "statusCode",
  });
});

/** @internal */
export type GetPurchaseOrderResponse$Outbound = {
  status_code: number;
  status: string;
  service: string;
  resource: string;
  operation: string;
  data: PurchaseOrder$Outbound;
};

/** @internal */
export const GetPurchaseOrderResponse$outboundSchema: z.ZodType<
  GetPurchaseOrderResponse$Outbound,
  z.ZodTypeDef,
  GetPurchaseOrderResponse
> = z.object({
  statusCode: z.number().int(),
  status: z.string(),
  service: z.string(),
  resource: z.string(),
  operation: z.string(),
  data: PurchaseOrder$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    statusCode: "status_code",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetPurchaseOrderResponse$ {
  /** @deprecated use `GetPurchaseOrderResponse$inboundSchema` instead. */
  export const inboundSchema = GetPurchaseOrderResponse$inboundSchema;
  /** @deprecated use `GetPurchaseOrderResponse$outboundSchema` instead. */
  export const outboundSchema = GetPurchaseOrderResponse$outboundSchema;
  /** @deprecated use `GetPurchaseOrderResponse$Outbound` instead. */
  export type Outbound = GetPurchaseOrderResponse$Outbound;
}

export function getPurchaseOrderResponseToJSON(
  getPurchaseOrderResponse: GetPurchaseOrderResponse,
): string {
  return JSON.stringify(
    GetPurchaseOrderResponse$outboundSchema.parse(getPurchaseOrderResponse),
  );
}

export function getPurchaseOrderResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetPurchaseOrderResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPurchaseOrderResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPurchaseOrderResponse' from JSON`,
  );
}
