/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";
import {
  SortDirection,
  SortDirection$inboundSchema,
  SortDirection$outboundSchema,
} from "./sortdirection.js";

/**
 * The field on which to sort the Leads
 */
export const LeadsSortBy = {
  CreatedAt: "created_at",
  UpdatedAt: "updated_at",
  Name: "name",
  FirstName: "first_name",
  LastName: "last_name",
  Email: "email",
} as const;
/**
 * The field on which to sort the Leads
 */
export type LeadsSortBy = ClosedEnum<typeof LeadsSortBy>;

export type LeadsSort = {
  /**
   * The field on which to sort the Leads
   */
  by?: LeadsSortBy | undefined;
  /**
   * The direction in which to sort the results
   */
  direction?: SortDirection | undefined;
};

/** @internal */
export const LeadsSortBy$inboundSchema: z.ZodNativeEnum<typeof LeadsSortBy> = z
  .nativeEnum(LeadsSortBy);

/** @internal */
export const LeadsSortBy$outboundSchema: z.ZodNativeEnum<typeof LeadsSortBy> =
  LeadsSortBy$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LeadsSortBy$ {
  /** @deprecated use `LeadsSortBy$inboundSchema` instead. */
  export const inboundSchema = LeadsSortBy$inboundSchema;
  /** @deprecated use `LeadsSortBy$outboundSchema` instead. */
  export const outboundSchema = LeadsSortBy$outboundSchema;
}

/** @internal */
export const LeadsSort$inboundSchema: z.ZodType<
  LeadsSort,
  z.ZodTypeDef,
  unknown
> = z.object({
  by: LeadsSortBy$inboundSchema.optional(),
  direction: SortDirection$inboundSchema.default("asc"),
});

/** @internal */
export type LeadsSort$Outbound = {
  by?: string | undefined;
  direction: string;
};

/** @internal */
export const LeadsSort$outboundSchema: z.ZodType<
  LeadsSort$Outbound,
  z.ZodTypeDef,
  LeadsSort
> = z.object({
  by: LeadsSortBy$outboundSchema.optional(),
  direction: SortDirection$outboundSchema.default("asc"),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LeadsSort$ {
  /** @deprecated use `LeadsSort$inboundSchema` instead. */
  export const inboundSchema = LeadsSort$inboundSchema;
  /** @deprecated use `LeadsSort$outboundSchema` instead. */
  export const outboundSchema = LeadsSort$outboundSchema;
  /** @deprecated use `LeadsSort$Outbound` instead. */
  export type Outbound = LeadsSort$Outbound;
}
